spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://47.112.7.167:3306/amy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      # 连接的最大生命周期，单位毫秒。应比数据库的 wait_timeout 小几分钟。
      # 这里设置为 55 分钟（3300000ms），比默认的 8 小时（28800s）短很多。
      max-lifetime: 3300000
      # 保持连接活跃的心跳间隔，单位毫秒。用于在连接空闲时定期向数据库发送“保活”信号。
      # 这有助于防止连接被数据库因空闲而关闭。该值必须小于 max-lifetime。
      keepalive-time: 240000
      # 连接池中最大连接数。根据应用负载调整，避免过大或过小。
      maximum-pool-size: 10
      # 验证连接是否有效的超时时间，单位毫秒。
      validation-timeout: 3000
  data:
    redis:
      host: 47.112.7.167
      port: 6379
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          # 最大连接数（默认8）
          max-active: 8
          # 最大空闲连接（默认8）
          max-idle: 8
          # 最小空闲连接（默认0）
          min-idle: 2
          # 最大等待时间（获取连接时的最长等待时间，单位毫秒，-1表示无限制）
          max-wait: 1000ms
